working_directory = "workspace" # use relative path under your $HOME dir

[shell]
program="/bin/zsh"
args=["-l", "-c", "tmux -f ~/.tmux.conf new-session"]

[window]
opacity = 0.8
blur = true
decorations = "full"
padding = {x = 5, y = 5}
startup_mode = "Maximized"

[keyboard]
bindings = [
    { key="Q", mods="command", action="None" }, # do not exit app
    { key="W", mods="command", action="None" }, # do not close window
]
